name: Continous Integration
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache dependencies (Unix)
        uses: actions/cache@v4
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Build
        run: |
          stack build
          mkdir build
          stack install --local-bin-path ./build

      - name: Package
        shell: bash
        run: |
          mkdir package
          cp ./build/http-haskel-exe ./package/
          cp ./config.cfg ./package/
          cp -r ./content ./package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog-build-${{ runner.os }}
          path: package
